version: '2.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    hostname: elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx8048m
      ELASTIC_PASSWORD: password
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    hostname: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elk

  filebeat:
    hostname: filebeat
    user: root
    image: "docker.elastic.co/beats/filebeat:7.13.1"
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/pipeline.json:/usr/share/filebeat/module/haproxy/log/ingest/pipline.json
      - ./filebeat/haproxy.log:/haproxy.log
    networks:
      - elk

networks:
  elk:
    driver: bridge
